from enum import Enum, unique


class ProductTags(str, Enum):
  LATEST_DEAL = "LATEST_DEAL"
  NEW_ARRIVALS = "NEW_ARRIVALS"
  MOST_VIEW  = "MOST_VIEW"
  ESSENTIAL  = "ESSENTIAL"
  TOP_SELLING  = "TOP_SELLING"
  MOST_PURCHASED  = "MOST_PURCHASED"
  SPECIAL_COLLECTION  = "SPECIAL_COLLECTION"
  SPECIAL_COLLECTION2  = "SPECIAL_COLLECTION2"
  ONGOING_SALE  = "ONGOING_SALE"

class ActiveStatus(str, Enum):
  ACTIVE = "ACTIVE"
  DEACTIVE = "DEACTIVE"